### ISSUE TITLE
Need explanation 

### ISSUE THREAD

**Issue by nageshpindi** [gramaziokohler/roslibpy#18]
Hi Everyone,
                 "service = roslibpy.Service(client, '/rosout/get_loggers', 'roscpp/GetLoggers')"
can anyone explain the use of last two parameters.
Thanks.

Summary.

## Expected Result
What you expected.

## Actual Result
What happened instead.

## Reproduction Steps
```python
import roslibpy

```

## System Information
Operating System name and version, ROS version, etc.

**Comment by gonzalocasas** [comment]
The API is documented, the parameter for the `Service` object are rather straightforward, the last two are `name`, i.e. the name of the service you want to call), and `service_type`, i.e. a service type definition, which basically means `.srv` file in your ROS setup that indicates the types of the request and the response of the service [see ROS wiki for more details](http://wiki.ros.org/Services#Service_Types).

Check the roslibpy docs for more:
https://roslibpy.readthedocs.io/en/latest/reference/index.html#services

**Comment by nageshpindi** [comment]
*Thanks for giving reply*

def success_callback(result):
    print('Service response: ', result['loggers'])

in result what they are printing and what does it means i need some
clarification, Below is my code i have written. According to document i
have been following.


import roslibpy

client = roslibpy.Ros(host='localhost', port=9090)
client.run()
client.on_ready(lambda: call_service())

service = roslibpy.Service(client,
'/rosplan_problem_interface/problem_generation_server', 'std_srvs/Empty')

def call_service():
    print('Calling service')
    request = roslibpy.ServiceRequest()
    service.call(request, success_callback, error_callback)
    return

def success_callback(result):
    print('Service response: ', result['rosplan_problem_interface'])
    return


def error_callback(result):
    print('Something went wrong')
    return

try:
    while True:
        pass
except KeyboardInterrupt:
    pass

client.terminate()
'''
if __name__=="__main__":

    success_callback(result)
*I'm getting error like this:*

Calling service
No handlers could be found for logger "roslibpy"

**Comment by gonzalocasas** [comment]
That is not an error, this is message from the `logging` module of the standard library (which you could easily find with a google search: ) and it only means you should add some logging handlers if you want to get logging output. Check the [official documentation](https://docs.python.org/2/howto/logging.html) for more details.

**Comment by nageshpindi** [comment]
Yes your correct Gonzalo but actually what should we put at result part
"result['rosplan_problem_interface']".

def success_callback(result):
    print('Service response: ', result['rosplan_problem_interface'])
    return
