### ISSUE TITLE
recommand newly translated doc in Chinese

### ISSUE THREAD

**Issue by XinArkh** [gramaziokohler/roslibpy#24]
Hi! I recently did some translation work in order to introduce this project to Chinese users by giving out a Chinese version document. I hope this could also be accepted by you.

website: [https://roslibpy-docs-zh.readthedocs.io](https://roslibpy-docs-zh.readthedocs.io)

repo: [https://github.com/XinArkh/roslibpy-docs-zh](https://github.com/XinArkh/roslibpy-docs-zh)

best regards,

**Comment by gonzalocasas** [comment]
@XinArkh cool stuff! thanks a lot! do you agree if we link it from the main help pages with a badge like this:

 ![](https://img.shields.io/badge/docs-%E4%B8%AD%E6%96%87-brightgreen.svg) 

or is it better to use this:

 ![](https://img.shields.io/badge/docs-zh-brightgreen.svg)
?
