### ISSUE TITLE
Can i also get a roslibpy for python 2.7 ?

### ISSUE THREAD

**Issue by aakashsehgal** [gramaziokohler/roslibpy#31]
I am integrating roslibpy with a system which only works with python 2.7. Currently I have roslibpy for python 3.6 which are creating some compatibility issues.

Is it possible to get roslibpy for python 2.7 or the same one would be sufficient to run with 3.6 and 2.7 ?

**Comment by gonzalocasas** [comment]
The same one runs on CPython 2.7 and 3.x and also IronPython 2.7:

![image](https://user-images.githubusercontent.com/933277/60433992-63d2b180-9c06-11e9-885d-e53854a49b9c.png)
