### ISSUE TITLE
`invoke test` with Python 3.7 fails: pytest unrecognized argument: --doctest-modules 

### ISSUE THREAD

**Issue by HWiese1980** [gramaziokohler/roslibpy#39]
Running `invoke test` results in the following error message:

```
Checking MANIFEST.in...
lists of files in version control and sdist match
Checking ReStructuredText formatting...
running check
Running flake8 python linter...
Checking python imports...
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --doctest-module
  inifile: /home/user/roslibpy/pytest.ini
  rootdir: /home/user/roslibpy
```

## Expected Result
No error message

## Actual Result
Error message, see above

## Reproduction Steps
Commit 4b1d3bdbb6ba7040b7f046d631d212eca1c56cf3 checked out

```
invoke test
```

## System Information
* ROS Kinetic Kame
* Ubuntu 16.04
* Python 3.7.4 (possible cause)

**Comment by gonzalocasas** [comment]
thanks for spotting this 👍  should be fixed now
