### ISSUE TITLE
How to publish image

### ISSUE THREAD

**Issue by Guo13** [gramaziokohler/roslibpy#50]
When I subscribe image from sensors by type sensor_msgs/Image, after base64 decoding I can process the image through opencv. After processing, how to publish it with right data type?

**Comment by gonzalocasas** [comment]
@Guo13 we just added some additional examples of `roslibpy` usage, including publish/subscribe images: https://roslibpy.readthedocs.io/en/latest/examples.html#advanced-examples

I hope it helps!
