### ISSUE TITLE
reset reconnect retry timer

### ISSUE THREAD

**Issue by chia-labradorsystems** [gramaziokohler/roslibpy#67]
I notice that in roslibpy

> Reconnect will be retried with an exponential back-off.

Is there any way that can rest the timer without modifying the code?

**Comment by gonzalocasas** [comment]
There are three methods that can be used to modify the retry behavior/timing: `set_max_delay`, `set_initial_delay`, and `set_max_retries`. They belong to the factory, so, you can use them like this: 
```
ros = roslibpy.Ros('127.0.0.1', 9090)
ros.factory.set_initial_delay(5)  # 5 seconds init delay
```

**Comment by gonzalocasas** [comment]
Let us know if that works for you, and if it does, we close the issue.

**Comment by chia-labradorsystems** [comment]
Thanks, let me test it :)

**Comment by chia-labradorsystems** [comment]
yes I think it works
I just notice that this is added since 1.1.0, and I was using 1.0.0

**Comment by gonzalocasas** [comment]
great! thanks!
